### ISSUE TITLE
Repository Ubuntu

### ISSUE THREAD

**Issue by githubdavide** [mnp/xspy#1]
Hi,
which repository should I use to install it on Ubuntu?
Thanks

**Comment by mnp** [comment]
I just gave it a try on the latest LTS, which was 16.04, but it should work on any version.  I updated the readme and added a Makefile with the command I used.  Let me know how it goes.

**Comment by githubdavide** [comment]
@mnp 
Ubuntu 17.10
Not working 
Do you need more information for the issue?
Regards

**Comment by mnp** [comment]
Ah, I just realized, 17.10 is not running X11 by default, it's running Wayland.  They have a way to turn on X11 though check this out: https://askubuntu.com/questions/961304/how-do-you-switch-from-wayland-back-to-xorg-in-ubuntu-17-10 - this matters to you because xspy needs to speak to an X11 server.

In other news, I saw they're moving *back* to X11 in 18.04: https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-18.04-Xorg-Default

**Comment by githubdavide** [comment]
Ok! thank you for your support
